<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AiKnowledgeBaseSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $entries = [
            // ---- OxNet Platform ----
            [
                'category'       => 'general',
                'question'       => 'What is OxNet?',
                'answer'         => "OxNet is a multi-tenant ISP management SaaS platform built for Kenyan ISPs. 🌐\n\nEach ISP gets their own:\n• Isolated database & subdomain (e.g., isp1.oxnet.co.ke)\n• Admin portal to manage customers, routers & billing\n• Customer self-service portal\n• M-Pesa Daraja payment integration\n\nPowered by MikroTik RouterOS API for PPPoE, hotspot, and DHCP management.",
                'keywords'       => json_encode(['oxnet', 'platform', 'saas', 'isp', 'what is']),
                'portal_context' => json_encode(['guest', 'admin', 'customer', 'community', 'login']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'general',
                'question'       => 'How does multi-tenancy work in OxNet?',
                'answer'         => "OxNet uses subdomain-per-tenant architecture. 🏗️\n\nEach ISP tenant gets:\n• A unique subdomain (e.g., myfastatv.oxnet.co.ke)\n• A fully isolated MySQL database\n• Their own admin credentials\n• Independent billing & customer data\n\nNo tenant can see another tenant's data — complete data isolation is guaranteed.",
                'keywords'       => json_encode(['multi-tenancy', 'subdomain', 'tenant', 'database', 'isolation']),
                'portal_context' => json_encode(['guest', 'admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- MikroTik ----
            [
                'category'       => 'mikrotik',
                'question'       => 'What MikroTik features does OxNet support?',
                'answer'         => "OxNet supports the following MikroTik features via RouterOS API: 🔧\n\n• PPPoE server management (add/remove users, set speeds)\n• Hotspot user management\n• DHCP server & lease management\n• Firewall rule management\n• Interface monitoring\n• Router auto-registration via scripts\n• Real-time connection status\n\nRouters connect securely using the MikroTik API on port 8728/8729.",
                'keywords'       => json_encode(['mikrotik', 'routeros', 'pppoe', 'hotspot', 'router', 'api']),
                'portal_context' => json_encode(['admin', 'community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'mikrotik',
                'question'       => 'How do I connect my MikroTik router to OxNet?',
                'answer'         => "To connect your MikroTik router to OxNet: 🔌\n\n1. Go to Admin Portal → Routers → Add Router\n2. Enter your router's IP address, API port (default: 8728), username & password\n3. Click 'Test Connection' to verify\n4. Once connected, OxNet can manage PPPoE users automatically\n\nMake sure the MikroTik API is enabled on the router: System → Services → API",
                'keywords'       => json_encode(['connect router', 'mikrotik setup', 'api port', 'add router']),
                'portal_context' => json_encode(['admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Billing / M-Pesa ----
            [
                'category'       => 'billing',
                'question'       => 'How does billing work in OxNet?',
                'answer'         => "OxNet uses M-Pesa STK Push for payments. 💳\n\nBilling flow:\n1. Customer selects a package in the Customer Portal\n2. An M-Pesa STK Push is sent to their phone\n3. Customer enters their M-Pesa PIN\n4. Payment confirms within seconds\n5. Subscription is automatically activated/renewed\n\nAll transactions are logged and can be viewed by the admin.",
                'keywords'       => json_encode(['billing', 'payment', 'mpesa', 'stk push', 'invoice']),
                'portal_context' => json_encode(['customer', 'admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'billing',
                'question'       => 'My M-Pesa payment went through but my internet is not working',
                'answer'         => "Sorry to hear that! Here's what to check: 😟\n\n1. **Wait 2-5 minutes** — activation can take a few minutes after payment\n2. **Check payment status** in Customer Portal → Payments\n3. **Reconnect your PPPoE** — disconnect and reconnect your router\n4. If still not working, **contact your ISP support** — they can manually verify & activate\n\nYour payment is safe and recorded. The ISP admin can check the M-Pesa transaction reference.",
                'keywords'       => json_encode(['payment went through', 'internet not working', 'mpesa paid', 'not activated', 'payment not reflecting']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'billing',
                'question'       => 'How do I renew my internet subscription?',
                'answer'         => "To renew your subscription: 🔄\n\n1. Log in to the Customer Portal\n2. Go to **My Subscription** or **Packages**\n3. Click **Renew** or **Buy Package**\n4. Select the package you want\n5. Click **Pay with M-Pesa**\n6. Enter your phone number and complete the STK Push\n\nYour subscription will be extended immediately after payment confirms! 🎉",
                'keywords'       => json_encode(['renew', 'subscription', 'extend', 'buy package', 'top up']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'billing',
                'question'       => 'What packages are available?',
                'answer'         => "Packages depend on your ISP. Common packages include: 📦\n\n• **Daily packages** — valid for 24 hours\n• **Weekly packages** — valid for 7 days\n• **Monthly packages** — valid for 30 days\n\nSpeeds and prices vary per ISP. Log in to your **Customer Portal → Packages** to see all available plans and their current prices in KES.",
                'keywords'       => json_encode(['packages', 'plans', 'pricing', 'daily', 'weekly', 'monthly', 'speeds']),
                'portal_context' => json_encode(['customer', 'guest']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Customer Portal ----
            [
                'category'       => 'navigation',
                'question'       => 'How do I log in to the customer portal?',
                'answer'         => "To log in to the Customer Portal: 🔐\n\n1. Go to your ISP's website (e.g., myfastatv.oxnet.co.ke)\n2. Click **Customer Login** or go to `/customer/login`\n3. Enter your **username** and **password** (given by your ISP)\n4. Click **Login**\n\nIf you forgot your password, use the **Forgot Password** link to reset via email or contact your ISP for help.",
                'keywords'       => json_encode(['login', 'customer login', 'sign in', 'access portal', 'password']),
                'portal_context' => json_encode(['customer', 'login', 'guest']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'navigation',
                'question'       => 'What can I do in the customer portal?',
                'answer'         => "The Customer Portal lets you: 🌟\n\n• 📊 View your current subscription & data usage\n• 💰 Pay for packages using M-Pesa\n• 🎫 Submit and track support tickets\n• 📋 View your payment history\n• 👤 Update your profile & change password\n• ⏰ See your subscription expiry countdown\n\nAll in one place, from any device!",
                'keywords'       => json_encode(['customer portal', 'what can i do', 'features', 'portal features']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Admin Portal ----
            [
                'category'       => 'navigation',
                'question'       => 'How do I add a new customer as an admin?',
                'answer'         => "To add a new customer/subscriber: 👤\n\n1. Go to **Admin Portal → Subscribers → Add New**\n2. Fill in: Name, Username, Password, Phone, Package\n3. Set the PPPoE credentials (username/password for their router)\n4. Click **Save**\n\nOxNet will automatically create the PPPoE user on your MikroTik router if connected!",
                'keywords'       => json_encode(['add customer', 'new subscriber', 'create user', 'add subscriber']),
                'portal_context' => json_encode(['admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'navigation',
                'question'       => 'How do I view reports in the admin portal?',
                'answer'         => "To view reports: 📊\n\n1. Go to **Admin Portal → Reports**\n2. Choose report type:\n   - **Revenue Report** — payments received by date range\n   - **Customer Report** — active/expired/new customers\n   - **Usage Report** — data consumption\n3. Set date range and click **Generate**\n4. Export to CSV if needed\n\nReports are updated in real-time!",
                'keywords'       => json_encode(['reports', 'revenue', 'analytics', 'export', 'csv']),
                'portal_context' => json_encode(['admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Connectivity ----
            [
                'category'       => 'connectivity',
                'question'       => 'My internet is slow, what should I do?',
                'answer'         => "If your internet is slow, try these steps: 🐌→🚀\n\n1. **Restart your router** — unplug, wait 30 seconds, plug back in\n2. **Check your package speed** — in Customer Portal → My Subscription\n3. **Test your speed** at fast.com or speedtest.net\n4. **Check connected devices** — too many devices can slow you down\n5. **Contact your ISP** — raise a support ticket if the issue persists\n\nCommon causes: network congestion, PPPoE session drop, router overheating.",
                'keywords'       => json_encode(['slow internet', 'slow speed', 'buffering', 'low bandwidth', 'speed']),
                'portal_context' => json_encode(['customer', 'community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'connectivity',
                'question'       => 'My internet keeps disconnecting',
                'answer'         => "Frequent disconnections are usually PPPoE-related: 🔌\n\n**Quick fixes:**\n1. Check your PPPoE username & password — one wrong character disconnects you\n2. Restart your MikroTik router\n3. Check the LAN cable connections\n4. Look for IP conflicts on your network\n\n**If the problem persists:**\n- Submit a support ticket via Customer Portal\n- Your ISP can check the RADIUS logs and MikroTik session\n- There may be a signal issue if you're on wireless backhaul",
                'keywords'       => json_encode(['disconnecting', 'keeps dropping', 'pppoe drop', 'disconnection', 'reconnect']),
                'portal_context' => json_encode(['customer', 'community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Community Portal ----
            [
                'category'       => 'community',
                'question'       => 'What is the OxNet Community Portal?',
                'answer'         => "The OxNet Community Portal is a forum for ISP professionals! 👥\n\nIt's a place where:\n• ISP admins share knowledge and tips\n• MikroTik experts answer questions\n• Network engineers discuss best practices\n• Users report bugs and feature requests\n\nAnyone can register for free and start participating. Topics include MikroTik, PPPoE, billing, networking, and more.",
                'keywords'       => json_encode(['community', 'forum', 'what is community', 'portal']),
                'portal_context' => json_encode(['community', 'guest']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'community',
                'question'       => 'How do I post in the community?',
                'answer'         => "To create a post in the community: ✍️\n\n1. **Register or log in** to the Community Portal\n2. Click **New Post** or go to a category and click **Post**\n3. Give your post a **title** and write your **content**\n4. Add **tags** to help others find it\n5. Click **Submit**\n\nYour post may be reviewed before appearing publicly (if moderation is enabled).\n\nTip: Be specific in your title — 'MikroTik PPPoE keeps dropping after 24h' gets better answers than 'Internet problem'!",
                'keywords'       => json_encode(['post', 'create post', 'new post', 'write', 'community post']),
                'portal_context' => json_encode(['community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Support ----
            [
                'category'       => 'support',
                'question'       => 'How do I contact support?',
                'answer'         => "You can reach support through: 📞\n\n1. **Support Ticket** — Customer Portal → Support → New Ticket (tracked, recommended)\n2. **WhatsApp** — Use the chat button (bottom-right of the page)\n3. **AI Assistant** — That's me! I can answer common questions instantly\n\nFor urgent network issues, your ISP admin can be reached directly. Super Admin support is available for platform-level issues.",
                'keywords'       => json_encode(['support', 'help', 'contact', 'ticket', 'assistance']),
                'portal_context' => json_encode(['customer', 'guest', 'admin', 'community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'support',
                'question'       => 'How do I submit a support ticket?',
                'answer'         => "To submit a support ticket: 🎫\n\n1. Log in to **Customer Portal**\n2. Go to **Support → New Ticket**\n3. Fill in:\n   - **Subject** — brief description of the issue\n   - **Category** — billing, connectivity, account, etc.\n   - **Priority** — low, medium, high\n   - **Description** — detailed explanation\n4. Click **Submit**\n\nYou'll receive updates via the portal. Your ISP team will respond as soon as possible.",
                'keywords'       => json_encode(['ticket', 'submit ticket', 'support ticket', 'raise ticket', 'complaint']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Security ----
            [
                'category'       => 'security',
                'question'       => 'Is my data safe on OxNet?',
                'answer'         => "Yes! OxNet takes security seriously: 🔒\n\n• **Database isolation** — each tenant has a completely separate database\n• **Encrypted credentials** — M-Pesa keys and router passwords are AES-256 encrypted\n• **HTTPS** — all traffic is encrypted in transit\n• **Rate limiting** — brute-force protection on all login pages\n• **CSRF protection** — all forms are protected\n• **Audit logs** — all admin actions are logged\n\nYour data is never shared with other tenants.",
                'keywords'       => json_encode(['security', 'data safe', 'encrypted', 'privacy', 'protection']),
                'portal_context' => json_encode(['guest', 'admin', 'customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Subscription Plans ----
            [
                'category'       => 'billing',
                'question'       => 'How do I upgrade my subscription plan?',
                'answer'         => "To upgrade your subscription plan as an ISP admin: ⬆️\n\n1. Go to **Admin Portal → Subscription**\n2. Click **View Plans** or **Upgrade**\n3. Choose a higher-tier plan\n4. Complete payment via M-Pesa STK Push\n\nHigher plans unlock more:\n• More subscribers\n• More routers\n• Advanced features (community portal, AI assistant, etc.)\n\nContact Super Admin if you need a custom plan.",
                'keywords'       => json_encode(['upgrade plan', 'subscription upgrade', 'higher plan', 'change plan']),
                'portal_context' => json_encode(['admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Swahili entries ----
            [
                'category'       => 'billing',
                'question'       => 'Nilikuwa nalipia lakini mtandao haujafunguka',
                'answer'         => "Pole kwa tatizo hilo! 😟\n\nJaribu hivi:\n1. **Subiri dakika 2-5** — uanzishaji unaweza kuchukua muda kidogo\n2. **Angalia malipo** kwenye Customer Portal → Payments\n3. **Unganisha tena PPPoE** — tenganisha na unganisha tena router yako\n4. Kama bado haifanyi kazi, **wasiliana na msaada wa ISP yako**\n\nMalipo yako yako salama na yamerekodiwa. 💰",
                'keywords'       => json_encode(['kulipa', 'mpesa', 'mtandao', 'haujafunguka', 'internet haifanyi']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'sw',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'connectivity',
                'question'       => 'Mtandao wangu ni polepole sana',
                'answer'         => "Shida ya mtandao wa polepole! Jaribu: 🐌\n\n1. **Anzisha tena router** — zima, subiri sekunde 30, washa tena\n2. **Angalia pakiti yako** — kasi inategemea pakiti uliyochagua\n3. **Pima kasi** kwenye fast.com\n4. **Punguza vifaa** vilivyounganishwa\n5. **Wasiliana na ISP** ukiwa na ticket ya msaada\n\nWasiliana naisi yako kwa msaada zaidi!",
                'keywords'       => json_encode(['polepole', 'mtandao slow', 'mbio', 'kasi ya internet']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'sw',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // ---- Additional entries ----
            [
                'category'       => 'navigation',
                'question'       => 'How do I reset my admin password?',
                'answer'         => "To reset your admin password: 🔑\n\n1. Go to your admin login page (subdomain.oxnet.co.ke/admin/login)\n2. Click **Forgot Password**\n3. Enter your registered email address\n4. Check your email for a reset link\n5. Follow the link and set a new password\n\nIf you don't receive the email within 5 minutes, check your spam folder.\nStill stuck? Contact Super Admin support.",
                'keywords'       => json_encode(['reset password', 'forgot password', 'admin password', 'change password']),
                'portal_context' => json_encode(['admin', 'login']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'general',
                'question'       => 'What is a PPPoE connection?',
                'answer'         => "PPPoE (Point-to-Point Protocol over Ethernet) is the connection type used for broadband internet in many Kenyan ISPs. 🌐\n\n**How it works:**\n• Your router sends a username & password to authenticate\n• The ISP's RADIUS server (FreeRADIUS) verifies credentials\n• A session is created with your assigned IP and speed\n\n**Why PPPoE?**\n• Better user management (per-user speed limits)\n• Easier billing integration\n• Session tracking & accounting\n\nOxNet manages all PPPoE users on your MikroTik automatically!",
                'keywords'       => json_encode(['pppoe', 'connection type', 'protocol', 'broadband', 'authenticate']),
                'portal_context' => json_encode(['admin', 'community', 'customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'billing',
                'question'       => 'Can I get a refund if I paid by mistake?',
                'answer'         => "Refund policies are set by your ISP, not OxNet. However: 💰\n\n1. **Contact your ISP immediately** via support ticket or WhatsApp\n2. Provide the **M-Pesa transaction code** (starts with letters like QHK...)\n3. Your ISP admin can verify and process a refund to your M-Pesa\n\n**Important:** M-Pesa transactions must be disputed within 24 hours.\n\nIf your ISP is unresponsive, contact Super Admin via the OxNet support channel.",
                'keywords'       => json_encode(['refund', 'paid by mistake', 'wrong payment', 'reverse', 'reverse payment']),
                'portal_context' => json_encode(['customer']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'mikrotik',
                'question'       => 'How do I configure PPPoE server on MikroTik?',
                'answer'         => "OxNet handles PPPoE user management automatically, but here's the MikroTik setup: ⚙️\n\n1. **PPPoE Server:** PPP → PPPoE Servers → Add (interface: ether1 or bridge)\n2. **IP Pool:** IP → Pool → Add (e.g., 10.0.0.2-10.0.0.254)\n3. **RADIUS Auth:** RADIUS → Add (server: your RADIUS IP, secret: shared key)\n4. **PPP Profile:** PPP → Profiles → Default-encryption (use-radius: yes)\n\nOnce RADIUS is configured, OxNet's FreeRADIUS handles all authentication automatically!",
                'keywords'       => json_encode(['pppoe server', 'mikrotik config', 'radius', 'setup', 'configure']),
                'portal_context' => json_encode(['admin', 'community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'general',
                'question'       => 'How do I register for OxNet as an ISP?',
                'answer'         => "To get your ISP on OxNet: 🚀\n\n1. Visit **oxnet.co.ke**\n2. Click **Get Started** or **Request Demo**\n3. Fill in your ISP details (name, email, subdomain preference)\n4. Choose a **pricing plan**\n5. Complete registration\n\nYou'll get:\n• Your own subdomain (yourname.oxnet.co.ke)\n• Admin portal access\n• 14-day free trial\n• Setup support\n\nContact: support@oxnet.co.ke",
                'keywords'       => json_encode(['register', 'sign up', 'get started', 'new isp', 'join', 'create account']),
                'portal_context' => json_encode(['guest', 'login']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'navigation',
                'question'       => 'Where can I see my subscription expiry date?',
                'answer'         => "Your subscription expiry is visible in multiple places: ⏰\n\n• **Customer Portal Dashboard** — countdown timer at the top\n• **My Subscription page** — full details\n• **Admin Portal** (for ISP admins) — subscription countdown in the navbar\n\nYou'll receive warnings when your subscription is about to expire (7 days, 3 days, 1 day before).\n\nRenew early to avoid service interruption!",
                'keywords'       => json_encode(['expiry', 'subscription date', 'expiry date', 'expires', 'countdown']),
                'portal_context' => json_encode(['customer', 'admin']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'security',
                'question'       => 'Why is my account locked?',
                'answer'         => "Accounts get locked after too many failed login attempts. 🔒\n\n**Common reasons:**\n1. Too many wrong passwords (5 failed attempts triggers lockout)\n2. Account suspended by admin for non-payment\n3. Account flagged for suspicious activity\n\n**How to unlock:**\n1. Wait 15 minutes (temporary lockout auto-releases)\n2. Use **Forgot Password** to reset\n3. Contact your ISP admin if suspended\n\nFor ISP admin accounts, contact Super Admin if locked.",
                'keywords'       => json_encode(['account locked', 'locked out', 'cannot login', 'suspended', 'blocked']),
                'portal_context' => json_encode(['customer', 'admin', 'login']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'general',
                'question'       => 'What browsers are supported?',
                'answer'         => "OxNet supports all modern browsers: 🌐\n\n✅ Google Chrome (recommended)\n✅ Mozilla Firefox\n✅ Microsoft Edge\n✅ Safari (Mac/iOS)\n✅ Mobile browsers (Android Chrome, iOS Safari)\n\nFor best performance:\n• Use Chrome or Edge on desktop\n• Ensure JavaScript is enabled\n• Clear cache if you see display issues\n\nOxNet is fully responsive and works great on smartphones! 📱",
                'keywords'       => json_encode(['browser', 'supported browsers', 'chrome', 'firefox', 'mobile']),
                'portal_context' => json_encode(['guest', 'customer', 'admin', 'community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'community',
                'question'       => 'How do I follow a community thread?',
                'answer'         => "To follow a thread and get notified of replies: 🔔\n\n1. Open the **post** you want to follow\n2. Click the **Follow** button (top right of the post)\n3. You'll be notified when someone replies\n\nYou can also **like** posts to show appreciation 👍\n\nTo see all threads you follow, go to **My Profile → Following**.",
                'keywords'       => json_encode(['follow', 'thread', 'notifications', 'community', 'subscribe post']),
                'portal_context' => json_encode(['community']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category'       => 'billing',
                'question'       => 'How does M-Pesa STK Push work?',
                'answer'         => "M-Pesa STK Push is a seamless payment experience: 📲\n\n1. You click **Pay with M-Pesa** and enter your phone number\n2. Safaricom sends a payment request directly to your phone\n3. A popup appears: \"OxNet ISP requests Ksh XXX\"\n4. You enter your **M-Pesa PIN** to confirm\n5. Safaricom processes the payment\n6. OxNet receives confirmation and activates your service\n\n**Total time:** Usually under 30 seconds! ⚡\n\nMake sure your M-Pesa is registered and has sufficient balance.",
                'keywords'       => json_encode(['stk push', 'mpesa stk', 'how to pay', 'mpesa payment', 'safaricom']),
                'portal_context' => json_encode(['customer', 'guest']),
                'language'       => 'en',
                'is_active'      => true,
                'created_by'     => 'seeder',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        DB::connection('mysql')->table('ai_knowledge_base')->insert($entries);

        $this->command->info('✅ AI Knowledge Base seeded with ' . count($entries) . ' entries.');
    }
}
