<?php

namespace App\Services;

use App\Models\Router;

class MikrotikScriptService
{
    public function generate(Router $router): string
    {
        $billingServerIp  = $this->resolveRadiusIp();
        $billingPublicKey = $this->resolveWgPublicKey();
        $wgPort           = $this->resolveWgPort();

        $callbackUrl  = rtrim(config('app.url'), '/') . '/api/router-callback';
        $provisionUrl = rtrim(config('app.url'), '/') . '/admin/provision/' . $router->ref_code;

        $routerName = preg_replace('/[^a-zA-Z0-9\-]/', '-', (string) $router->name);
        $routerName = preg_replace('/-{2,}/', '-', $routerName);
        $routerName = trim($routerName, '-') ?: 'MikroTik-Router';

        $billingDomain = $router->billing_domain
            ?: env('BILLING_DOMAIN', parse_url(config('app.url'), PHP_URL_HOST) ?: 'billing.local');

        $wanIface      = $router->wan_interface      ?: env('WAN_INTERFACE', 'ether1');
        $customerIface = $router->customer_interface ?: 'bridge1';

        $pppoePoolRange   = $router->pppoe_pool_range   ?: '10.10.1.1-10.10.1.254';
        $hotspotPoolRange = $router->hotspot_pool_range ?: '10.20.1.1-10.20.1.254';

        $wgOctet            = (($router->id % 253) + 2);
        $wgRouterIp         = "10.255.255.{$wgOctet}/32";
        $wgServerIp         = '10.255.255.1/32';
        $wgSubnet           = '10.255.255.0/24';
        $wgAllowedAddresses = "{$wgServerIp},{$wgSubnet}";

        $radiusSecret   = (string) $router->radius_secret;
        $scriptFilename = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $router->name)) . '-mikrotik.rsc';

        $mgmtIps    = env('MANAGEMENT_IPS', '192.168.88.1,10.0.0.1');
        $mgmtIpList = array_values(array_filter(array_map('trim', explode(',', $mgmtIps))));

        $L = [];

        // ── Header ────────────────────────────────────────────────────────────
        $L[] = '# ============================================================';
        $L[] = "# MikroTik Configuration Script for: {$router->name}";
        $L[] = '# Generated by iNettotik ISP Billing System';
        $L[] = '# Date: ' . now()->format('Y-m-d H:i:s');
        $L[] = '#';
        $L[] = '# Bootstrap one-liner (run ONCE on a fresh router):';
        $L[] = "#   /tool fetch url=\"{$provisionUrl}\" dst-path=\"{$scriptFilename}\"";
        $L[] = "#   /import {$scriptFilename}";
        $L[] = '# ============================================================';
        $L[] = '';

        // ── Variables ─────────────────────────────────────────────────────────
        $L[] = '# --- Configuration Variables ---';
        $L[] = ":local routerName \"{$routerName}\"";
        $L[] = ":local billingServerIP \"{$billingServerIp}\"";
        $L[] = ":local wgRouterIP \"{$wgRouterIp}\"";
        $L[] = ":local wgPort {$wgPort}";
        $L[] = ":local billingPublicKey \"{$billingPublicKey}\"";
        $L[] = ":local callbackURL \"{$callbackUrl}\"";
        $L[] = ":local provisionURL \"{$provisionUrl}\"";
        $L[] = ":local scriptFilename \"{$scriptFilename}\"";
        $L[] = ":local radiusSecret \"{$radiusSecret}\"";
        $L[] = ":local wanInterface \"{$wanIface}\"";
        $L[] = ":local customerInterface \"{$customerIface}\"";
        $L[] = ":local pppoePoolRange \"{$pppoePoolRange}\"";
        $L[] = ":local hotspotPoolRange \"{$hotspotPoolRange}\"";
        $L[] = ":local billingDomain \"{$billingDomain}\"";
        $L[] = ':local wgSubnet "10.255.255.0/24"';
        $L[] = '';

        // ── System Identity ───────────────────────────────────────────────────
        $L[] = '# --- System Identity ---';
        $L[] = "/system identity set name=\"{$routerName}\"";
        $L[] = '';

        // ── Customer Bridge ───────────────────────────────────────────────────
        $L[] = '# --- Customer Interface (Bridge) ---';
        $L[] = ":if ([:len [/interface bridge find name=\"{$customerIface}\"]] = 0) do={";
        $L[] = "  /interface bridge add name=\"{$customerIface}\" comment=\"Customer Bridge - iNettotik\" disabled=no";
        $L[] = '}';
        $L[] = '';

        // ── RADIUS ────────────────────────────────────────────────────────────
        $L[] = '# --- RADIUS Client ---';
        $L[] = '/radius remove [find]';
        $L[] = "/radius add address={$billingServerIp} secret=\"{$radiusSecret}\" service=ppp,hotspot,login";
        $L[] = '/radius incoming set accept=yes port=3799';
        $L[] = '';

        // ── IP Pools ──────────────────────────────────────────────────────────
        $L[] = '# --- IP Address Pools ---';
        $L[] = '/ip pool remove [find name="pppoe-pool"]';
        $L[] = "/ip pool add name=\"pppoe-pool\" ranges={$pppoePoolRange}";
        $L[] = '/ip pool remove [find name="hotspot-pool"]';
        $L[] = "/ip pool add name=\"hotspot-pool\" ranges={$hotspotPoolRange}";
        $L[] = '';

        // ── PPP Profiles ──────────────────────────────────────────────────────
        $L[] = '# --- PPP Profiles ---';
        $L[] = '/ppp profile remove [find name="pppoe-radius"]';
        $L[] = '/ppp profile add name="pppoe-radius" local-address=pppoe-pool remote-address=pppoe-pool use-compression=no only-one=yes';
        $L[] = '';

        // ── PPPoE Server ──────────────────────────────────────────────────────
        $L[] = '# --- PPPoE Server ---';
        $L[] = "/interface pppoe-server server remove [find interface=\"{$customerIface}\"]";
        $L[] = "/interface pppoe-server server add interface=\"{$customerIface}\" service-name=\"pppoe-service\" default-profile=\"pppoe-radius\" authentication=mschap2,mschap1,chap,pap one-session-per-host=yes disabled=no";
        $L[] = '';

        // ── Hotspot ───────────────────────────────────────────────────────────
        $L[] = '# --- Hotspot Server ---';
        $L[] = "/ip hotspot remove [find interface=\"{$customerIface}\"]";
        $L[] = '/ip hotspot profile remove [find name="hsprof-radius"]';
        $L[] = "/ip hotspot profile add name=\"hsprof-radius\" hotspot-address=192.168.2.1 dns-name=\"{$billingDomain}\" use-radius=yes radius-location-id=\"{$routerName}\" login-by=http-pap,http-chap http-cookie-lifetime=1d";
        $L[] = "/ip hotspot add interface=\"{$customerIface}\" address-pool=hotspot-pool profile=\"hsprof-radius\" name=\"hotspot-server\" disabled=no";
        $L[] = '';

        // ── Walled Garden ─────────────────────────────────────────────────────
        $L[] = '# --- Hotspot Walled Garden ---';
        $L[] = '/ip hotspot walled-garden remove [find]';
        $L[] = "/ip hotspot walled-garden add server=\"hotspot-server\" dst-host=\"{$billingDomain}\" action=allow";
        $L[] = "/ip hotspot walled-garden add server=\"hotspot-server\" dst-host=\"*.{$billingDomain}\" action=allow";
        $L[] = "/ip hotspot walled-garden ip add server=\"hotspot-server\" dst-address={$billingServerIp} action=accept";
        $L[] = '';

        // ── NAT ───────────────────────────────────────────────────────────────
        $L[] = '# --- NAT Masquerade ---';
        $L[] = '/ip firewall nat remove [find comment="ISP-NAT"]';
        $L[] = "/ip firewall nat add chain=srcnat out-interface=\"{$wanIface}\" action=masquerade comment=\"ISP-NAT\"";
        $L[] = '';

        // ── PCQ Queues ────────────────────────────────────────────────────────
        $L[] = '# --- PCQ Queue Types ---';
        $L[] = '/queue type remove [find name="pcq-download"]';
        $L[] = '/queue type add name="pcq-download" kind=pcq pcq-rate=0 pcq-classifier=dst-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $L[] = '/queue type remove [find name="pcq-upload"]';
        $L[] = '/queue type add name="pcq-upload" kind=pcq pcq-rate=0 pcq-classifier=src-address pcq-dst-address-mask=32 pcq-src-address-mask=32';
        $L[] = '/queue tree remove [find name="Download"]';
        $L[] = "/queue tree add name=\"Download\" parent=\"{$wanIface}\" queue=pcq-download";
        $L[] = '/queue tree remove [find name="Upload"]';
        $L[] = '/queue tree add name="Upload" parent=global queue=pcq-upload';
        $L[] = '';

        // ── Firewall ──────────────────────────────────────────────────────────
        $L[] = '# --- Firewall Rules ---';
        $L[] = '';
        $L[] = '# Drop invalid connections';
        $L[] = '/ip firewall filter remove [find comment="ISP-DROP-INVALID"]';
        $L[] = '/ip firewall filter add chain=forward connection-state=invalid action=drop comment="ISP-DROP-INVALID"';
        $L[] = '';
        $L[] = '# Client-to-client isolation';
        $L[] = '/ip firewall filter remove [find comment="ISP-NO-CLIENT2CLIENT"]';
        $L[] = "/ip firewall filter add chain=forward in-interface=\"{$customerIface}\" out-interface=\"{$customerIface}\" action=drop comment=\"ISP-NO-CLIENT2CLIENT\"";
        $L[] = '';
        $L[] = '# SSH brute-force protection';
        $L[] = '/ip firewall filter remove [find comment="ISP-BRUTE-SSH"]';
        $L[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new src-address-list=ssh-bruteforce action=drop comment="ISP-BRUTE-SSH"';
        $L[] = '/ip firewall filter remove [find comment="ISP-DETECT-SSH"]';
        $L[] = '/ip firewall filter add chain=input protocol=tcp dst-port=22 connection-state=new action=add-src-to-address-list address-list=ssh-bruteforce address-list-timeout=1h comment="ISP-DETECT-SSH"';
        $L[] = '';

        if (!empty($mgmtIpList)) {
            $L[] = '# Management IP Whitelist';
            $L[] = '/ip firewall address-list remove [find list="mgmt-allowed"]';
            foreach ($mgmtIpList as $ip) {
                $L[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$ip} comment=\"Management\"";
            }
            $L[] = "/ip firewall address-list add list=\"mgmt-allowed\" address={$billingServerIp} comment=\"Billing Server\"";
            $L[] = '/ip firewall filter remove [find comment="ISP-MGMT-ALLOW"]';
            $L[] = '/ip firewall filter add chain=input src-address-list=mgmt-allowed action=accept comment="ISP-MGMT-ALLOW"';
            $L[] = '/ip firewall filter remove [find comment="ISP-MGMT-DROP"]';
            $L[] = "/ip firewall filter add chain=input action=drop src-address-list=!mgmt-allowed in-interface=\"{$wanIface}\" protocol=tcp dst-port=22,8291 comment=\"ISP-MGMT-DROP\"";
            $L[] = '';
        }

        // ── Services ──────────────────────────────────────────────────────────
        $L[] = '# --- Services ---';
        $L[] = '/ip service disable telnet,ftp,www-ssl,api-ssl';
        $L[] = '/ip service enable ssh,winbox,api,www';
        $L[] = '/ip service set ssh port=22';
        $L[] = '/ip service set winbox port=8291';
        $L[] = '/ip service set api port=8728';
        $L[] = '/ip service set www port=80';
        $L[] = '';

        // ── NTP ───────────────────────────────────────────────────────────────
        $L[] = '# --- NTP Client ---';
        $L[] = ':do { /system ntp client set enabled=yes } on-error={}';
        $L[] = ':do { /system ntp client servers add address=216.239.35.0 } on-error={}';
        $L[] = ':do { /system ntp client servers add address=216.239.35.4 } on-error={}';
        $L[] = '';

        // ── DNS ───────────────────────────────────────────────────────────────
        $L[] = '# --- DNS ---';
        $L[] = '/ip dns set allow-remote-requests=yes servers=8.8.8.8,1.1.1.1';
        $L[] = '';

        // ── WireGuard ─────────────────────────────────────────────────────────
        //
        // FIX: The previous :foreach loop to remove orphaned interfaces caused
        // "input does not match any value of interface" on fresh routers because
        // RouterOS cannot remove an interface that is currently referenced by
        // other config (IP addresses, peers). The safe approach is:
        //
        //  1. Remove peers by comment first (safe on fresh router — finds nothing)
        //  2. Remove IP addresses by comment (safe — finds nothing on fresh)
        //  3. Remove the named interface only (safe — finds nothing on fresh)
        //  4. Create fresh interface, IP, peer
        //
        // We do NOT use :foreach to remove unnamed/orphaned interfaces because
        // on RouterOS 7.x the find filter on WireGuard interfaces returns internal
        // object IDs (*11 etc.) that cannot be passed to remove in a loop safely.
        // Orphaned interfaces only accumulate if the script aborts mid-run, which
        // the cleanup in steps 1-3 now prevents.
        //
        $L[] = '# --- WireGuard Management Tunnel (wg-billing) ---';
        $L[] = '';
        $L[] = '# Remove existing peers, addresses and interface by name/comment';
        $L[] = '# (safe on fresh router — [find] returns empty, nothing is removed)';
        $L[] = '/interface wireguard peers remove [find comment="iNettotik Billing Server"]';
        $L[] = '/ip address remove [find comment="iNettotik VPN IP"]';
        $L[] = '/interface wireguard remove [find name="wg-billing"]';
        $L[] = '';
        $L[] = '# Create fresh WireGuard interface';
        $L[] = "/interface wireguard add name=\"wg-billing\" listen-port={$wgPort} mtu=1420 comment=\"iNettotik Billing Tunnel\"";
        $L[] = '';
        $L[] = '# Assign VPN IP';
        $L[] = "/ip address add address={$wgRouterIp} interface=\"wg-billing\" comment=\"iNettotik VPN IP\"";
        $L[] = '';
        $L[] = '# Add billing server as peer';
        $L[] = '/interface wireguard peers add interface="wg-billing" \\';
        $L[] = "    public-key=\"{$billingPublicKey}\" \\";
        $L[] = "    endpoint-address={$billingServerIp} \\";
        $L[] = "    endpoint-port={$wgPort} \\";
        $L[] = "    allowed-address=\"{$wgAllowedAddresses}\" \\";
        $L[] = '    persistent-keepalive=25s \\';
        $L[] = '    comment="iNettotik Billing Server"';
        $L[] = '';
        $L[] = '# Allow WireGuard UDP through firewall';
        $L[] = '/ip firewall filter remove [find comment="ISP-WG-BILLING"]';
        $L[] = "/ip firewall filter add chain=input protocol=udp dst-port={$wgPort} action=accept comment=\"ISP-WG-BILLING\"";
        $L[] = '';

        // ── Auto-Register ─────────────────────────────────────────────────────
        $L[] = '# --- Auto-Register with Billing Server ---';
        $L[] = ':local wanIP ""';
        $L[] = ':do {';
        $L[] = "    :set wanIP [/ip address get [find interface=\"{$wanIface}\"] address]";
        $L[] = '    :set wanIP [:pick $wanIP 0 [:find $wanIP "/"]]';
        $L[] = '} on-error={';
        $L[] = "    :put \"WARNING: Could not detect WAN IP on {$wanIface}\"";
        $L[] = '}';
        $L[] = '';
        $L[] = ':local vpnIP ""';
        $L[] = ':do {';
        $L[] = '    :set vpnIP [/ip address get [find interface="wg-billing"] address]';
        $L[] = '    :set vpnIP [:pick $vpnIP 0 [:find $vpnIP "/"]]';
        $L[] = '} on-error={';
        $L[] = '    :put "WARNING: Could not detect VPN IP"';
        $L[] = '}';
        $L[] = '';
        $L[] = ':local routerPubKey ""';
        $L[] = ':do {';
        $L[] = '    :set routerPubKey [/interface wireguard get [find name="wg-billing"] public-key]';
        $L[] = '} on-error={}';
        $L[] = '';
        $L[] = ':do {';
        $L[] = '    /tool fetch url=$callbackURL \\';
        $L[] = '        http-method=post \\';
        $L[] = '        http-header-field="Content-Type: application/json" \\';
        $L[] = '        http-data=("{\"router_name\":\"" . $routerName . "\",\"wan_ip\":\"" . $wanIP . "\",\"vpn_ip\":\"" . $vpnIP . "\",\"radius_secret\":\"" . $radiusSecret . "\",\"wg_public_key\":\"" . $routerPubKey . "\"}") \\';
        $L[] = '        output=none';
        $L[] = '    :put "=============================================="';
        $L[] = '    :put "  Router registered in iNettotik database!"';
        $L[] = '    :put "  WAN IP:     $wanIP"';
        $L[] = '    :put "  VPN IP:     $vpnIP"';
        $L[] = '    :put "  WG PubKey:  $routerPubKey"';
        $L[] = '    :put "=============================================="';
        $L[] = '} on-error={';
        $L[] = '    :put "WARNING: Could not reach billing server at $callbackURL"';
        $L[] = '    :put "  WAN IP:    $wanIP"';
        $L[] = '    :put "  VPN IP:    $vpnIP"';
        $L[] = '    :put "  WG PubKey: $routerPubKey"';
        $L[] = '    :put "  Secret:    $radiusSecret"';
        $L[] = '}';
        $L[] = '';

        // ── Scheduler ─────────────────────────────────────────────────────────
        $L[] = '# --- Scheduled Auto-Update (nightly at 03:00) ---';
        $L[] = '/system scheduler remove [find name="iNettotik-AutoUpdate"]';
        $L[] = '/system scheduler add \\';
        $L[] = '    name="iNettotik-AutoUpdate" \\';
        $L[] = '    interval=1d \\';
        $L[] = '    start-time=03:00:00 \\';
        $L[] = '    on-event=("/tool fetch url=\"' . $provisionUrl . '\" dst-path=\"' . $scriptFilename . '\"; /import ' . $scriptFilename . '") \\';
        $L[] = '    comment="iNettotik: auto-fetch and apply latest config from billing server"';
        $L[] = '';
        $L[] = ':put "=============================================="';
        $L[] = ':put "  iNettotik provisioning complete!"';
        $L[] = ':put "  Auto-update scheduled daily at 03:00."';
        $L[] = ':put "=============================================="';

        return implode("\n", $L) . "\n";
    }

    protected function resolveRadiusIp(): string
    {
        $ip = env('RADIUS_SERVER_IP', '');
        if ($ip !== '') return trim($ip);
        $host = parse_url(config('app.url'), PHP_URL_HOST) ?: '';
        return filter_var($host, FILTER_VALIDATE_IP) ? $host : '127.0.0.1';
    }

    protected function resolveWgPublicKey(): string
    {
        return trim(env('WG_SERVER_PUBLIC_KEY', 'KEY_NOT_CONFIGURED_SET_WG_SERVER_PUBLIC_KEY_IN_ENV'));
    }

    protected function resolveWgPort(): int
    {
        return (int) env('WG_PORT', 51820);
    }
}