@extends('admin.layouts.app')
@section('title', 'Add Router')

@section('content')
<div class="row justify-content-center">
    <div class="col-sm-12 mb-3">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h5 class="mb-0">Add Router</h5>
            </div>
            <a href="{{ route('admin.isp.routers.index') }}" class="btn btn-outline-secondary">
                <i class="bx bx-arrow-back me-1"></i> Back
            </a>
        </div>
    </div>

    <div class="col-md-8">
        @if($errors->any())
        <div class="alert alert-danger alert-dismissible" role="alert">
            <ul class="mb-0">
                @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        @endif

        <div class="alert alert-info d-flex align-items-center mb-4" role="alert">
            <i class="bx bx-info-circle me-2 fs-5"></i>
            <div>
                <strong>Auto-generated by system:</strong> RADIUS Secret, PPPoE/Hotspot pools, and network config are auto-generated. WAN IP and VPN IP are automatically detected when you run the generated MikroTik script on the router.
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h6 class="mb-0"><i class="bx bx-router me-2"></i>Router Details</h6>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.isp.routers.store') }}" method="POST">
                    @csrf

                    <div class="mb-3">
                        <label class="form-label fw-semibold">Router Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                               value="{{ old('name') }}" placeholder="e.g. Nairobi CBD Router" required>
                        @error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-semibold">Router Model</label>
                        <select name="model" class="form-select @error('model') is-invalid @enderror">
                            <option value="">-- Select Model --</option>
                            @foreach([
                                'hAP ac²','hAP ac³','RB750Gr3 (hEX)','RB760iGS (hEX S)',
                                'CCR1009-7G-1C-1S+','CCR1036-12G-4S','CCR2004-1G-12S+2XS',
                                'RB4011iGS+','RB5009UG+S+IN','CRS326-24G-2S+','Other'
                            ] as $m)
                            <option value="{{ $m }}" {{ old('model') == $m ? 'selected' : '' }}>{{ $m }}</option>
                            @endforeach
                        </select>
                        @error('model')<div class="invalid-feedback">{{ $message }}</div>@enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-semibold">RouterOS Version</label>
                        <select name="routeros_version" class="form-select @error('routeros_version') is-invalid @enderror">
                            <option value="">-- Select Version --</option>
                            @foreach([
                                'RouterOS v6.49','RouterOS v6.49.10',
                                'RouterOS v7.12','RouterOS v7.13','RouterOS v7.14',
                                'RouterOS v7.15','RouterOS v7.16'
                            ] as $v)
                            <option value="{{ $v }}" {{ old('routeros_version') == $v ? 'selected' : '' }}>{{ $v }}</option>
                            @endforeach
                        </select>
                        @error('routeros_version')<div class="invalid-feedback">{{ $message }}</div>@enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-semibold">Notes</label>
                        <textarea name="notes" rows="3" class="form-control @error('notes') is-invalid @enderror"
                                  placeholder="Optional notes about this router...">{{ old('notes') }}</textarea>
                        @error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror
                    </div>

                    <div class="mb-4">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active"
                                   {{ old('is_active', 1) ? 'checked' : '' }}>
                            <label class="form-check-label fw-semibold" for="is_active">Active</label>
                        </div>
                    </div>

                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-primary">
                            <i class="bx bx-save me-1"></i> Create Router
                        </button>
                        <a href="{{ route('admin.isp.routers.index') }}" class="btn btn-outline-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection